#ifndef _MAIN_H
#define _MAIN_H

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/ipc.h>
#include <sys/msg.h>
#include <sys/shm.h>

typedef int bool;
#define TRUE 1
#define FALSE 0

//Message structure.
typedef struct msgbuf{
	long type;					// Message type
	char userSender[30];		//Sender
	char userRecipient[30];		//Recipient
	int signal;					//Signal acknowledgment message, and send special data
	time_t timeSend;			//The receiver's time of the message, it is generated by the server
	char message[200];			//Message from customer to another customer
	int msgPriority;			//Message priority, 1 - Not important, 10 - Very important
} message_buf;

enum message_types {
	LOGIN = 20,		//LOGIN IN
	LOGOUT,			//LOG OUT
	SHOWALL,		//VIEW ALL CLIENTS
	SHOWACTIVE,		//VIEW ALL ACITVE CLIENTS
	SHOWGROUPS,		//VIEW GROUPS
	SHOWMEMBERS,	//VIEW ALL CLIENTS BELONG TO GROUP
	BLACKLIST,		//ADD CLIENTS TO BLACKLIST
	BLACKLISTG,		//ADD GROUP TO BLACKLIST
	JOIN,			//JOIN GROUP
	LEAVE,			//LEAVE GROUP
	MSG,			//MESSAGE TO CLIENT
	MSGG,			//MESSAGE TO ALL CLIENT FROM GROUP
	RECMSG,			//RETURN INFORMATION, CONTROLS
	RMSG			//MESSAGE FROM CLIENT / GROUP
};

#endif
